slam_toolbox:
  ros__parameters:
    use_sim_time: true
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    ceres_minimum_trust_region_radius: 5e-04
    ceres_maximum_trust_region_radius: 5e+04
    ceres_maximum_num_iterations: 10
    ceres_parameter_tolerance: 1e-08
    ceres_function_tolerance: 1e-06
    ceres_gradient_tolerance: 1e-10
    ceres_linear_solver_tolerance: 1e-04
    ceres_max_num_line_search_direction_steps: 20
    ceres_max_num_line_search_step_size_iterations: 10
    ceres_line_search_direction_type: LBFGS
    ceres_line_search_armijo_constant: 1e-4
    ceres_min_lm_num_iterations: 10
    ceres_max_lm_num_iterations: 20
    ceres_enough_lm_iterations_for_good_solution: 10
    ceres_max_num_iterations_before_refine: 10
    ceres_threads: 1
    ceres_linear_solver_num_threads: 1
    ceres_preconditioner_num_threads: 1
    ceres_residual_block_timeout: 100
    debug_logging: false
    mode: mapping
    map_frame: map
    base_frame: base_footprint
    odom_frame: odom
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 5.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 37500000
    enable_interactive_mode: true
    scan_topic: /scan
    use_scan_matching: true
    use_scan_barycenter: true
    do_interactive_loop: true
    do_loop_closing: true
    loop_merge_minimum_cluster_size: 10
    loop_merge_maximum_cluster_size: 10000
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_coarse: 0.1
    link_match_minimum_response_fine: 0.1
    link_search_maximum_distance: 1.5
    loop_search_minimum_distance: 0.5
    loop_search_maximum_distance: 3.0
    loop_search_configuration_space: 0.2
    free_space_reflection_angle: 0.15
    use_response_expansion: true
